# Generated by Django 5.1.15 on 2026-04-22 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=100)),
                ('asset', models.CharField(blank=True, max_length=50)),
                ('total_balance', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('from_field', models.CharField(blank=True, db_column='from_source', max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('asset_group', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.dailyupload')),
            ],
            options={
                'indexes': [models.Index(fields=['upload', 'from_field', 'category'], name='core_balanc_upload__3acaad_idx'), models.Index(fields=['upload', 'asset_group'], name='core_balanc_upload__96708a_idx'), models.Index(fields=['upload', 'type'], name='core_balanc_upload__4c3caa_idx')],
            },
        ),
    ]
